### PR TITLE
Add Paperclip to README

### PR DESCRIPTION
**Pull request by crcn**
I'd like to add something!

### CODE REVIEW

**Comment by RobinCsl** [comment]
That looks really cool! Thanks for sharing!!

The compiler is written in Rust and transforms the `.pc` files into React components. Did I get this right?

**Comment by crcn** [comment]
It's a bit of a mix. The Rust engine is used to parse `.pc` files and is also used to render realtime previews. There's another module written in JS that translates parsed templates (from the Rust engine) to React code.

**Comment by RobinCsl** [comment]
Nice! Thank you for indulging my curiosity.

I will need to read your README to find out more about it, as this mixed approach sounds interesting.

Thanks again for your contribution!

**Comment by crcn** [comment]
No problem! There's not much in the README yet explaining how everything works, but I'll add that in a bit.

**Pull request merged**
